[package]
name = "ease-off"
version = "0.1.0"
edition = "2021"
rust-version = "1.80.0"

[dependencies.tokio]
version = "1.0.1"
features = ["rt", "time"]
optional = true

[dependencies.async-std]
version = "1"
optional = true

[dependencies.rand]
version = "0.8.5"
