[package]
name = "ease-off"
version = "0.1.0"
edition = "2021"
rust-version = "1.80.0"

[dependencies.tokio]
version = "1.0.1"
features = ["rt", "time"]
optional = true

[dependencies.rand]
version = "0.8.5"

[[example]]
name = "tokio"
required-features = ["tokio"]

[dev-dependencies.tokio]
version = "1.39.3"
features = ["rt", "time", "macros"]
